/* Autogenerated by png2wx.pl on Sat Jan  8 21:19:13 2022 */
#ifndef SENSOR_PLUGIN_ICONS_H
#define SENSOR_PLUGIN_ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *windowsSensorLogo;

#endif /* SENSOR_PLUGIN_ICONS_H */
